package Mailfull::Setup::Postfix;

use strict;
use warnings;
use diagnostics;


##############################
# generate main.cf
##############################
sub setup {
    my $self = shift;

    print "generate postfix configuration, save into $Mailfull::Core::Cfg->{dir_etc}\n";

    my $uid = getpwnam $Mailfull::Core::Cfg->{username};
    my $gid = getgrnam $Mailfull::Core::Cfg->{groupname};

    if ( ! defined($uid) || ! defined($gid) ) {
        return ;
    }

    my $time = localtime(time);

    my $conf = << "___EOL___";
# Generated by mailfull on $time

#myhostname = host.example.com

# 自ドメイン名
#   ・append_dot_mydomain有効時にドメイン名がついていないとメールアドレスにつけられる
#   ・mydestinationのデフォルト値で「localhost.$mydomain」として使用される
mydomain = \$myhostname

# ローカルで投函されたメールがどのドメインからくるように見えるかを指定する
# デフォルトではローカルマシン名、\$myhostnameが使われる。
myorigin = \$mydomain

# Postfixシステムがlistenすべきであるすべてのネットワークアドレスを指定する。
# master.cfファイルでIPアドレスをサーバ名の前につけることによって、inet_interfaces設定を上書きすることができる
inet_interfaces = all

# このマシンが他のマシンに転送せずにローカルに配送するドメインを指定する。
mydestination = \$myhostname, localhost.\$mydomain, localhost, \$mydomain

# メールの中継元となるクライアント
# ・host: (安全: ローカルマシンのみを許可)
# ・subnet: (デフォルト: サブネットワークを許可)
mynetworks_style = host

# ユーザ名と拡張アドレス(user+foo)の間の区切り。
recipient_delimiter = -

# エンベロープ情報を含む、バイト単位のメッセージの最大サイズ
message_size_limit = 10240000

# local(8)の個々のメールボックスまたはmaildirの最大サイズ。ゼロの場合、制限なし
mailbox_size_limit = 51200000

# バーチャルドメイン(virtualdomain)での一つのメールボックスの最大容量
virtual_mailbox_limit = 51200000

# 受信するドメイン名、複数のドメインを受診する場合は","で区切り受信するドメインを記載する
virtual_mailbox_domains = hash:$Mailfull::Core::Cfg->{path_domains}

# 受信したメールがスプールされるディレクトリを指定
virtual_mailbox_base = $Mailfull::Core::Cfg->{dir_data}

# \$virtual_transportメール転送transportを使って配送されるドメインのリスト。
# \$virtual_mailbox_mapsで受信者アドレスを確認し、存在しない受信者宛のメールを拒否する。
virtual_mailbox_maps = $Mailfull::Core::Cfg->{path_maildirs}

# 目的のメールボックスに書き込むときに使われるUIDを検索する場合に使うマップ
virtual_uid_maps = static:$uid

# 目的のメールボックスに書き込むときに使われるGIDを検索するあ愛に使うマップ
virtual_gid_maps = static:$gid

# バーチャルドメインのユーザーリスト
# virtual_alias_domainsで指定したバーチャルドメインに含まれるメールアドレスと、
# そのメールアドレスを実際に送信する宛先をルックアップテーブル形式で指定する。
virtual_alias_maps = hash:$Mailfull::Core::Cfg->{path_destinations}

# 受信者アドレスから(メッセージ配送transport、next-hop配送先)へのマッピングを持つ、オプションの検索テーブル
transport_maps = regexp:$Mailfull::Core::Cfg->{path_localtable}

# local(8)配送で使われるエイリアスデータベース
# エイリアスデータベースを変更したら、"postalias /etc/aliases"か"newaliases"を走らせて必要なDBMまたはDBファイルを作る。
alias_maps = hash:/etc/aliases, hash:$Mailfull::Core::Cfg->{path_forwards}

# local(8)配送のエイリアスデータベース。
# "newaliases"や"sendmail -bi"で更新される。
# $alias_mapsで指定されるテーブルすべてがローカルファイルである必要はないため、これは別の設定パラメータになっている
alias_database = hash:/etc/aliases, hash:$Mailfull::Core::Cfg->{path_forwards}

# Postfix SMTPサーバのSASL認証を有効にする。デフォルトでは認証を使わない。
smtpd_sasl_auth_enable = yes

# SASL認証realmの名前
smtpd_sasl_local_domain = \$myhostname

# Postfix SMTPサーバがMAIL FROMコマンドの場面で適用する、オプションの制限
# デフォルトではすべてを許可。
# ・check_sender_access: access(5)データベースでMAIL FROMアドレスやドメイン、親ドメイン、localpart@を検索し、actionを実行
# ・check_sender_mx_access: access(5)データベースでMAIL FROMアドレスのMXホストを検索し、対応するactionを実行する
# ・check_sender_ns_access: access(5)データベースでMAIL FROMアドレスのDNSサーバを検索し、対応するactionを実行する
# ・reject_authenticated_sender_login_mismatch: 認証されたクライアントのみにreject_sender_login_mismatch制限を強制する
# ・reject_non_fqdn_sender: MAIL FROMアドレスがRFCで要求されるような完全修飾ドメイン形式ではない場合に、要求を拒否する
# ・reject_rhsbl_sender rbl_domain=d.d.d.d: MAIL FROMドメインがrbl_domain以下のAレコードld.d.d.dでリストアップされている時に、要求を拒否する
# ・reject_sender_login_mismatch: $smtpd_sender_login_mapsがMAIL FROMアドレスの所有者を指定しているが、クライアントがMAIL FROMアドレスの所有者とし(SASL)ログインしていない場合に、要求を拒否する
# ・refect_unauthenticated_sender_login_mismatch: 認証されていないクライアントのみにreject_sender_login_mismatch制限を強制する
# ・reject_unknown_sender_domain: MAIL FROMアドレスにDNS　AまたはMXレコードがなく、Postfixがその送信者アドレスの最終配信先ではない場合に、要求を拒否する
# ・reject_unlisted_sender: MAIL FROMアドレスがドメインクラスに対する有効な受信者リストにない場合に、要求を拒否する
# reject_unverified_sender: MAIL FROMアドレスが合うんすするとわかっている場合や、送信者アドレスの配送先に到達できない場合に、要求を拒否する
smtpd_recipient_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination

# SMTPサーバで使用するSASL認証の有効化
smtpd_sasl_type = dovecot

# SASL認証デーモンのソケットファイル
smtpd_sasl_path = private/auth

# 鍵指定
smtpd_tls_cert_file = /etc/pki/dovecot/certs/dovecot.pem
smtpd_tls_key_file = /etc/pki/dovecot/private/dovecot.pem
#smtpd_tls_CAfile =
smtpd_tls_session_cache_database = btree:/etc/postfix/smtpd_scache
___EOL___

    Mailfull::Utils::File->touch("$Mailfull::Core::Cfg->{dir_etc}/main.cf.sample", $Mailfull::Core::Cfg->{umask_etc});
    open (my $fh_out, '>', "$Mailfull::Core::Cfg->{dir_etc}/main.cf.sample") or die "$!";
    print $fh_out $conf;
    close($fh_out) or die "$!";
}



1;
